# Generated by Django 3.2.18 on 2023-09-15 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationname', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=300)),
                ('licenseno', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('certificate', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=300)),
                ('pincode', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('slotno', models.CharField(max_length=50)),
                ('EVSTATIONS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evapp.evstation')),
            ],
        ),
        migrations.CreateModel(
            name='Slotbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('slotno', models.CharField(max_length=50)),
                ('SLOTS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evapp.slots')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=1000)),
                ('servicecharge', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('WORKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evapp.workers')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=10)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=50)),
                ('SLOTS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evapp.slots')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evapp.login')),
            ],
        ),
        migrations.AddField(
            model_name='evstation',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evapp.login'),
        ),
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt', models.CharField(max_length=1000)),
                ('reply', models.CharField(max_length=1000)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evapp.users')),
                ('WORKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evapp.workers')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('reply', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=10)),
                ('POST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evapp.post')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('msg', models.CharField(max_length=1000)),
                ('FROMID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fuser', to='Evapp.login')),
                ('TOID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tuser', to='Evapp.login')),
            ],
        ),
    ]
