# Generated by Django 3.2.18 on 2023-09-18 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evapp', '0002_auto_20230918_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='USER',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Evapp.users'),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='SLOTS',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Evapp.slots'),
        ),
    ]
