# Generated by Django 3.2.18 on 2023-09-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evapp', '0003_auto_20230918_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotbooking',
            name='slotno',
        ),
    ]
