# Generated by Django 3.2.18 on 2023-09-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evapp', '0004_remove_slotbooking_slotno'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='status',
            field=models.CharField(default='', max_length=30),
        ),
    ]
