# Generated by Django 3.2.18 on 2023-09-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evapp', '0005_slotbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
