# Generated by Django 3.2.18 on 2023-09-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evapp', '0006_feedback_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='msg',
        ),
        migrations.AddField(
            model_name='chat',
            name='message',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
