# Generated by Django 3.2.18 on 2023-10-19 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evapp', '0008_service_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_booking',
            name='type_of_service',
        ),
    ]
