# Generated by Django 3.2.18 on 2023-10-27 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evapp', '0009_remove_service_booking_type_of_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='EVSTATIONS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Evapp.evstation'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Evapp.login'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(default='', max_length=50),
        ),
    ]
