# Generated by Django 3.2.18 on 2023-11-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evapp', '0010_auto_20231027_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='slots',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
